### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by xkcdjerry** [uuk0/mcpython-4#9]
Basic crafting:wood crafting does not work
(I think this should be implemented first, without a worktable, what can players do?)

**Comment by uuk0** [comment]
Wood planks are in the game, crafting table not and also the recipe is still giving exceptions.
I will add tags (which are needed for advanced recipes) and fix the crafting system.
I don't know how well the crafting table will work without some other changes to crafting system

**Comment by xkcdjerry** [comment]
Anyway, can you fix the bug about not being even able to craft wood?

**Comment by uuk0** [comment]
I will try to implement it next, but maybe it may take longer than a few days.
I could try an fast-fix by adding new recipes for planks, but it would be only temporary

**Comment by xkcdjerry** [comment]
OK.Can you try the fast-fix for me to test out more bugs?Thanks!
PS:How does crafting work?

**Comment by uuk0** [comment]
Ok, I will add it in a few minutes

**Comment by uuk0** [comment]
Crafting (how it works):
recipes are stored as .json files in resourcepacks/1.14.4.jar/data/minecraft/recipes
they contain information what type of recipe it is, what you need and what the output is.
crafting recipes are seperated into two big categories: shaped (you need the exact grid) and shapeless (only the items must be in the grid, order is not checked).
The item check system handles also so called "tags" which are groups of items definied in resourepacks/1.14.4.jar/data/minecraft/tags/item & /block.
The tag check is not implemented so not all recipes are working
Also, only shapeless recipes are working because of an bug in the system and the not implemented system which will remove items from input when output is taken.

In order to fix this, the tag system must be implemented and shaped recipes must be fixed

**Comment by xkcdjerry** [comment]
Thank you,but shouldn't wood be counted as shapeless recipes?

**Comment by uuk0** [comment]
Yes, it is, but it is using an tag for the log, the wood (with side texture on all sides) and the stripped variants

**Comment by xkcdjerry** [comment]
hmm, I think I can fix the remover,where is it?

**Comment by uuk0** [comment]
What do you mean with "remover"?

**Comment by xkcdjerry** [comment]
That's the system which removes the input when the output is broken

**Comment by uuk0** [comment]
for shapeless recipes it is working, for shaped recipes there is an bug in checking the recipe state which I have not fixed yet

**Comment by xkcdjerry** [comment]
How to fix it?

**Comment by uuk0** [comment]
At the moment, I have no clue what's going wrong in the check system

But I have now finished the work-around for the log recipes

**Comment by xkcdjerry** [comment]
maybe you can split out a Recipe class with a check method
I will download it soon.

**Comment by uuk0** [comment]
Crafting should now be fully implemented
You can test it and if everything is working fine, close this issue

**Comment by xkcdjerry** [comment]
Axes are not working:

![image](https://user-images.githubusercontent.com/49294431/65946982-dfdccf80-e469-11e9-8c8e-2bd2d2fa2d7d.png)

PS:What's this rendering bug?
![image](https://user-images.githubusercontent.com/49294431/65946930-c76cb500-e469-11e9-9678-414844cf9758.png)

**Comment by xkcdjerry** [comment]
Oh,here is the error message:
can't find item named minecraft:wooden_hoe
can't find item named minecraft:wooden_hoe
can't find item named minecraft:wooden_axe
can't find item named minecraft:wooden_axe
can't find item named minecraft:wooden_axe
can't find item named minecraft:wooden_axe

**Comment by uuk0** [comment]
The error message & the bug comes simply from the non-implementation of the item that is used as output. If you want to add those tools, you can create an file at resourcepacks/minecraft/assets/factory/item/Item[YourItemNameOrItemGroupName].json with an list of item names to add. They will be generated by the system automaticly.

**Comment by uuk0** [comment]
But if you want full tool functionality, we have to implement an tool system & brake time system first

**Comment by xkcdjerry** [comment]
emm,OK
but we can just use a dummy:tool in hand break time=bare hand break time
PS:What's that rendering bug?

**Comment by uuk0** [comment]
I don't realy now. I have found it by helping in https://github.com/fogleman/Minecraft/issues/103. It seems an problem with OpenGL's distance system which decides which color to draw. It incorrectly draws the color (0, 0, 0, 0) from the leave texture only, no behind alpha textures. This occures not ontop of normal blocks because we are using two diffrent rendering batches for those with alpha and those without.

**Comment by xkcdjerry** [comment]
Frankly, I have no idea what your are saying...

**Comment by uuk0** [comment]
I have no clue what is going wrong with the rendering system

**Comment by xkcdjerry** [comment]
Items vanished?
![image](https://user-images.githubusercontent.com/49294431/66015701-27b13480-e506-11e9-8ebe-372ad6cf4352.png)

**Comment by uuk0** [comment]
Are they showing up in inventory?

**Comment by xkcdjerry** [comment]
sorry, I didn't notice.

**Comment by uuk0** [comment]
There is an bug with items in the hotbar of the player not showing correct. If you open your inventory with E and close it with ESC, are they than visible?

**Comment by xkcdjerry** [comment]
I will try it in the morning
